#!/usr/bin/env bash

curl https://garagehq.deuxfleurs.fr/_releases/v0.9.3/x86_64-unknown-linux-musl/garage > garage
chmod u+x garage
trap 'rm garage' EXIT
nfpm pkg --packager deb
nfpm pkg --packager rpm
